spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: idankob.helper@gmail.com
    password: yzyshcinromjotlx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true