name: Create release.

on:
  push:
    branches: ['30-releases']

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: bootJar

  relese:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Release
        uses: IdanKoblik/action-automatic-releases@v0.2
        with:
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ github.run_number }}"
          title: Release
          files: |
            ./gitlab-monitor.jar